//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PedidosSSCC.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PedidosSSCC.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aprobado automático.
        /// </summary>
        public static string AprobadoAutomatico {
            get {
                return ResourceManager.GetString("AprobadoAutomatico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aceptar.
        /// </summary>
        public static string Boton_Aceptar {
            get {
                return ResourceManager.GetString("Boton_Aceptar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Añadir concepto.
        /// </summary>
        public static string Boton_AgregarConcepto {
            get {
                return ResourceManager.GetString("Boton_AgregarConcepto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Añadir configuración.
        /// </summary>
        public static string Boton_AgregarConfiguracion {
            get {
                return ResourceManager.GetString("Boton_AgregarConfiguracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Añadir proveedor.
        /// </summary>
        public static string Boton_AnadirProveedor {
            get {
                return ResourceManager.GetString("Boton_AnadirProveedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar.
        /// </summary>
        public static string Boton_Buscar {
            get {
                return ResourceManager.GetString("Boton_Buscar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Búsqueda avanzada.
        /// </summary>
        public static string Boton_BusquedaAvanzada {
            get {
                return ResourceManager.GetString("Boton_BusquedaAvanzada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrar.
        /// </summary>
        public static string Boton_Cerrar {
            get {
                return ResourceManager.GetString("Boton_Cerrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descargar Plantilla.
        /// </summary>
        public static string Boton_DescargarPlantilla {
            get {
                return ResourceManager.GetString("Boton_DescargarPlantilla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exportar Conceptos.
        /// </summary>
        public static string Boton_ExportarConceptos {
            get {
                return ResourceManager.GetString("Boton_ExportarConceptos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exportar Configuración.
        /// </summary>
        public static string Boton_ExportarConfiguracion {
            get {
                return ResourceManager.GetString("Boton_ExportarConfiguracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar.
        /// </summary>
        public static string Boton_Guardar {
            get {
                return ResourceManager.GetString("Boton_Guardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Importar Excel.
        /// </summary>
        public static string Boton_ImportarExcel {
            get {
                return ResourceManager.GetString("Boton_ImportarExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Limpiar.
        /// </summary>
        public static string Boton_Limpiar {
            get {
                return ResourceManager.GetString("Boton_Limpiar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar Configuración.
        /// </summary>
        public static string Config_Editar {
            get {
                return ResourceManager.GetString("Config_Editar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Menú de acciones.
        /// </summary>
        public static string Dropdown_MenuAcciones {
            get {
                return ResourceManager.GetString("Dropdown_MenuAcciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Activo.
        /// </summary>
        public static string Etiqueta_Activo {
            get {
                return ResourceManager.GetString("Etiqueta_Activo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar Empresa.
        /// </summary>
        public static string Etiqueta_AgregarEmpresa {
            get {
                return ResourceManager.GetString("Etiqueta_AgregarEmpresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Año del concepto.
        /// </summary>
        public static string Etiqueta_AnoConcepto {
            get {
                return ResourceManager.GetString("Etiqueta_AnoConcepto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aplicación.
        /// </summary>
        public static string Etiqueta_Aplicacion {
            get {
                return ResourceManager.GetString("Etiqueta_Aplicacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Conceptos Aprobados!.
        /// </summary>
        public static string Etiqueta_Aprobados {
            get {
                return ResourceManager.GetString("Etiqueta_Aprobados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar palabras clave.
        /// </summary>
        public static string Etiqueta_Buscar {
            get {
                return ResourceManager.GetString("Etiqueta_Buscar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Campos obligatorios: .
        /// </summary>
        public static string Etiqueta_CamposObligatorios {
            get {
                return ResourceManager.GetString("Etiqueta_CamposObligatorios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cantidad.
        /// </summary>
        public static string Etiqueta_Cantidad {
            get {
                return ResourceManager.GetString("Etiqueta_Cantidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Categoría.
        /// </summary>
        public static string Etiqueta_Categoria {
            get {
                return ResourceManager.GetString("Etiqueta_Categoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Categoría Calculada.
        /// </summary>
        public static string Etiqueta_CategoriaCalculada {
            get {
                return ResourceManager.GetString("Etiqueta_CategoriaCalculada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CIF *.
        /// </summary>
        public static string Etiqueta_CifObligatorio {
            get {
                return ResourceManager.GetString("Etiqueta_CifObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contacto.
        /// </summary>
        public static string Etiqueta_Contacto {
            get {
                return ResourceManager.GetString("Etiqueta_Contacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correción Facturación.
        /// </summary>
        public static string Etiqueta_CorrecionFacturacion {
            get {
                return ResourceManager.GetString("Etiqueta_CorrecionFacturacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Coste Hora Fuera de alcance.
        /// </summary>
        public static string Etiqueta_CosteHoraF {
            get {
                return ResourceManager.GetString("Etiqueta_CosteHoraF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción.
        /// </summary>
        public static string Etiqueta_Descripcion {
            get {
                return ResourceManager.GetString("Etiqueta_Descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dirección.
        /// </summary>
        public static string Etiqueta_Direccion {
            get {
                return ResourceManager.GetString("Etiqueta_Direccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Duración.
        /// </summary>
        public static string Etiqueta_Duracion {
            get {
                return ResourceManager.GetString("Etiqueta_Duracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar Módulo.
        /// </summary>
        public static string Etiqueta_EditarModulo {
            get {
                return ResourceManager.GetString("Etiqueta_EditarModulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email.
        /// </summary>
        public static string Etiqueta_Email {
            get {
                return ResourceManager.GetString("Etiqueta_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Empresa.
        /// </summary>
        public static string Etiqueta_Empresa {
            get {
                return ResourceManager.GetString("Etiqueta_Empresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Empresa a facturar.
        /// </summary>
        public static string Etiqueta_EmpresaFacturar {
            get {
                return ResourceManager.GetString("Etiqueta_EmpresaFacturar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado.
        /// </summary>
        public static string Etiqueta_Estado {
            get {
                return ResourceManager.GetString("Etiqueta_Estado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha Fin.
        /// </summary>
        public static string Etiqueta_FechaFin {
            get {
                return ResourceManager.GetString("Etiqueta_FechaFin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha Inicio.
        /// </summary>
        public static string Etiqueta_FechaInicio {
            get {
                return ResourceManager.GetString("Etiqueta_FechaInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Generar Conceptos.
        /// </summary>
        public static string Etiqueta_GenerarConceptos {
            get {
                return ResourceManager.GetString("Etiqueta_GenerarConceptos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Grupo Asignado.
        /// </summary>
        public static string Etiqueta_GrupoAsignado {
            get {
                return ResourceManager.GetString("Etiqueta_GrupoAsignado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Importe.
        /// </summary>
        public static string Etiqueta_Importe {
            get {
                return ResourceManager.GetString("Etiqueta_Importe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Importe unitario.
        /// </summary>
        public static string Etiqueta_ImporteUnitario {
            get {
                return ResourceManager.GetString("Etiqueta_ImporteUnitario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Licencias Reemplazo.
        /// </summary>
        public static string Etiqueta_LicenciasReemplazo {
            get {
                return ResourceManager.GetString("Etiqueta_LicenciasReemplazo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mes del concepto.
        /// </summary>
        public static string Etiqueta_MesConcepto {
            get {
                return ResourceManager.GetString("Etiqueta_MesConcepto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        public static string Etiqueta_Nombre {
            get {
                return ResourceManager.GetString("Etiqueta_Nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre Módulo.
        /// </summary>
        public static string Etiqueta_NombreModulo {
            get {
                return ResourceManager.GetString("Etiqueta_NombreModulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre MS.
        /// </summary>
        public static string Etiqueta_NombreMS {
            get {
                return ResourceManager.GetString("Etiqueta_NombreMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre *.
        /// </summary>
        public static string Etiqueta_NombreObligatorio {
            get {
                return ResourceManager.GetString("Etiqueta_NombreObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Oficina.
        /// </summary>
        public static string Etiqueta_Oficina {
            get {
                return ResourceManager.GetString("Etiqueta_Oficina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Presupuesto.
        /// </summary>
        public static string Etiqueta_Presupuesto {
            get {
                return ResourceManager.GetString("Etiqueta_Presupuesto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Presupuesto consumido.
        /// </summary>
        public static string Etiqueta_PresupuestoConsumido {
            get {
                return ResourceManager.GetString("Etiqueta_PresupuestoConsumido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proveedor.
        /// </summary>
        public static string Etiqueta_Proveedor {
            get {
                return ResourceManager.GetString("Etiqueta_Proveedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Razón Social *.
        /// </summary>
        public static string Etiqueta_RazonSocialObligatorio {
            get {
                return ResourceManager.GetString("Etiqueta_RazonSocialObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Conceptos Rechazados!.
        /// </summary>
        public static string Etiqueta_Rechazados {
            get {
                return ResourceManager.GetString("Etiqueta_Rechazados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccionar Archivo Excel:.
        /// </summary>
        public static string Etiqueta_SeleccionarArchivoExcel {
            get {
                return ResourceManager.GetString("Etiqueta_SeleccionarArchivoExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tarea.
        /// </summary>
        public static string Etiqueta_Tarea {
            get {
                return ResourceManager.GetString("Etiqueta_Tarea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tarea - Empresa.
        /// </summary>
        public static string Etiqueta_TareaEmpresa {
            get {
                return ResourceManager.GetString("Etiqueta_TareaEmpresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tarea de Soporte.
        /// </summary>
        public static string Etiqueta_TareaSoporte {
            get {
                return ResourceManager.GetString("Etiqueta_TareaSoporte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo Entidad.
        /// </summary>
        public static string Etiqueta_TipoEntidad {
            get {
                return ResourceManager.GetString("Etiqueta_TipoEntidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipos de entidad permitidos.
        /// </summary>
        public static string Etiqueta_TiposEnte {
            get {
                return ResourceManager.GetString("Etiqueta_TiposEnte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Título.
        /// </summary>
        public static string Etiqueta_Titulo {
            get {
                return ResourceManager.GetString("Etiqueta_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ubicación.
        /// </summary>
        public static string Etiqueta_Ubicacion {
            get {
                return ResourceManager.GetString("Etiqueta_Ubicacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario.
        /// </summary>
        public static string Etiqueta_Usuario {
            get {
                return ResourceManager.GetString("Etiqueta_Usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Validar.
        /// </summary>
        public static string Etiqueta_Validar {
            get {
                return ResourceManager.GetString("Etiqueta_Validar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Máximo Grupo.
        /// </summary>
        public static string Etqueta_MaximoGrupo {
            get {
                return ResourceManager.GetString("Etqueta_MaximoGrupo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Año *.
        /// </summary>
        public static string Modal_Ano {
            get {
                return ResourceManager.GetString("Modal_Ano", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        public static string Modal_Boton_Cancelar {
            get {
                return ResourceManager.GetString("Modal_Boton_Cancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exportar.
        /// </summary>
        public static string Modal_Boton_Exportar {
            get {
                return ResourceManager.GetString("Modal_Boton_Exportar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Subir y Procesar.
        /// </summary>
        public static string Modal_Boton_SubirProcesar {
            get {
                return ResourceManager.GetString("Modal_Boton_SubirProcesar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DETALLE CONCEPTO PENDIENTE DE APROBAR.
        /// </summary>
        public static string Modal_ConceptosPendientes {
            get {
                return ResourceManager.GetString("Modal_ConceptosPendientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mes *.
        /// </summary>
        public static string Modal_Mes {
            get {
                return ResourceManager.GetString("Modal_Mes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccionar Archivo Excel:.
        /// </summary>
        public static string Modal_SeleccionarArchivo {
            get {
                return ResourceManager.GetString("Modal_SeleccionarArchivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tarea.
        /// </summary>
        public static string Modal_Tarea {
            get {
                return ResourceManager.GetString("Modal_Tarea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exportar Conceptos a Excel.
        /// </summary>
        public static string Modal_Titulo_Exportar {
            get {
                return ResourceManager.GetString("Modal_Titulo_Exportar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Importar Archivo Excel.
        /// </summary>
        public static string Modal_Titulo_Importar {
            get {
                return ResourceManager.GetString("Modal_Titulo_Importar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar....
        /// </summary>
        public static string Placeholder_Buscar {
            get {
                return ResourceManager.GetString("Placeholder_Buscar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Año.
        /// </summary>
        public static string Tabla_Ano {
            get {
                return ResourceManager.GetString("Tabla_Ano", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cantidad.
        /// </summary>
        public static string Tabla_Cantidad {
            get {
                return ResourceManager.GetString("Tabla_Cantidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción.
        /// </summary>
        public static string Tabla_Descripcion {
            get {
                return ResourceManager.GetString("Tabla_Descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Empresa.
        /// </summary>
        public static string Tabla_Empresa {
            get {
                return ResourceManager.GetString("Tabla_Empresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado.
        /// </summary>
        public static string Tabla_Estado {
            get {
                return ResourceManager.GetString("Tabla_Estado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Importe total.
        /// </summary>
        public static string Tabla_ImporteTotal {
            get {
                return ResourceManager.GetString("Tabla_ImporteTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inversión.
        /// </summary>
        public static string Tabla_Inversion {
            get {
                return ResourceManager.GetString("Tabla_Inversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mes.
        /// </summary>
        public static string Tabla_Mes {
            get {
                return ResourceManager.GetString("Tabla_Mes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tarea.
        /// </summary>
        public static string Tabla_Tarea {
            get {
                return ResourceManager.GetString("Tabla_Tarea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Conceptos de Facturación.
        /// </summary>
        public static string Titulo_ConceptosFacturacion {
            get {
                return ResourceManager.GetString("Titulo_ConceptosFacturacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configuración.
        /// </summary>
        public static string Titulo_Configuracion {
            get {
                return ResourceManager.GetString("Titulo_Configuracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar Contrato CAU.
        /// </summary>
        public static string Titulo_Contratos {
            get {
                return ResourceManager.GetString("Titulo_Contratos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contratos de soporte.
        /// </summary>
        public static string Titulo_ContratosSoporte {
            get {
                return ResourceManager.GetString("Titulo_ContratosSoporte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos Generales.
        /// </summary>
        public static string Titulo_DatosGenerales {
            get {
                return ResourceManager.GetString("Titulo_DatosGenerales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Departamentos.
        /// </summary>
        public static string Titulo_Departamentos {
            get {
                return ResourceManager.GetString("Titulo_Departamentos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gestión de Grupo.
        /// </summary>
        public static string Titulo_GestionGrupo {
            get {
                return ResourceManager.GetString("Titulo_GestionGrupo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gestión de Proveedor.
        /// </summary>
        public static string Titulo_GestionProveedor {
            get {
                return ResourceManager.GetString("Titulo_GestionProveedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Licencias.
        /// </summary>
        public static string Titulo_Licencias {
            get {
                return ResourceManager.GetString("Titulo_Licencias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Los siguientes campos son obligatorios:.
        /// </summary>
        public static string Toast_CamposObligatorios {
            get {
                return ResourceManager.GetString("Toast_CamposObligatorios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Todos los campos obligatorios deben ser completados..
        /// </summary>
        public static string Toast_CamposObligatoriosGeneral {
            get {
                return ResourceManager.GetString("Toast_CamposObligatoriosGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor, seleccione al menos un concepto para aprobar..
        /// </summary>
        public static string Toast_ConceptosAprobar {
            get {
                return ResourceManager.GetString("Toast_ConceptosAprobar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a e-Mail: No se encontro la persona destinataria del email.
        /// </summary>
        public static string Toast_EmailNoEncontrado {
            get {
                return ResourceManager.GetString("Toast_EmailNoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error en la llamada al servicio. Ver log para mas detalles..
        /// </summary>
        public static string Toast_ErrorServicio {
            get {
                return ResourceManager.GetString("Toast_ErrorServicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al enviar el email. Ver log para mas detalles..
        /// </summary>
        public static string Toast_ErrorServicioEmail {
            get {
                return ResourceManager.GetString("Toast_ErrorServicioEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Operacion realizada correctamente.
        /// </summary>
        public static string Toast_OperacionOk {
            get {
                return ResourceManager.GetString("Toast_OperacionOk", resourceCulture);
            }
        }
    }
}
