//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Comun.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se han guardado los datos, aunque se ha superado el nº de elementos definido para esta tarea-empresa..
        /// </summary>
        public static string alertCantidadTareaEmpresaSuperada {
            get {
                return ResourceManager.GetString("alertCantidadTareaEmpresaSuperada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se han guardado los datos, aunque se ha superado el presupuesto definido para esta tarea-empresa..
        /// </summary>
        public static string alertPresupuestoTareaEmpresaSuperado {
            get {
                return ResourceManager.GetString("alertPresupuestoTareaEmpresaSuperado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aprobado automático.
        /// </summary>
        public static string AprobadoAutomatico {
            get {
                return ResourceManager.GetString("AprobadoAutomatico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aceptar.
        /// </summary>
        public static string btnAceptar {
            get {
                return ResourceManager.GetString("btnAceptar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        public static string btnCancelar {
            get {
                return ResourceManager.GetString("btnCancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar sesión.
        /// </summary>
        public static string btnIniciarSesion {
            get {
                return ResourceManager.GetString("btnIniciarSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solicitar.
        /// </summary>
        public static string btnSolicitar {
            get {
                return ResourceManager.GetString("btnSolicitar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Está seguro de que desea APROBAR la solicitud?.
        /// </summary>
        public static string confirmAprobarWorkflow {
            get {
                return ResourceManager.GetString("confirmAprobarWorkflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Está seguro de que desea eliminar el registro?.
        /// </summary>
        public static string confirmEliminarRegistro {
            get {
                return ResourceManager.GetString("confirmEliminarRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Está seguro de que desea emitir la factura? Se bloqueará la factura y se solicitará su aprobación si es requerida..
        /// </summary>
        public static string confirmEmitirFactura {
            get {
                return ResourceManager.GetString("confirmEmitirFactura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Está seguro de que desea emitir el pedido? Se bloqueará el pedido y se solicitará su aprobación si es requerida..
        /// </summary>
        public static string confirmEmitirPedido {
            get {
                return ResourceManager.GetString("confirmEmitirPedido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Está seguro de que desea RECHAZAR la solicitud?.
        /// </summary>
        public static string confirmRechazarWorkflow {
            get {
                return ResourceManager.GetString("confirmRechazarWorkflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El texto introducido no coincide con el texto de la imagen..
        /// </summary>
        public static string errCaptcha {
            get {
                return ResourceManager.GetString("errCaptcha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se puede eliminar la tarea ya que tiene empresas asociadas..
        /// </summary>
        public static string errEliminarTareaExistenEmpresas {
            get {
                return ResourceManager.GetString("errEliminarTareaExistenEmpresas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya existe una factura con el nº &apos;{0}&apos;.
        /// </summary>
        public static string errFacturaNumExistente {
            get {
                return ResourceManager.GetString("errFacturaNumExistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No existen facturas que cumplan los criterios indicados para realizar el enlace contable.
        /// </summary>
        public static string errFacturasEnlaceContable {
            get {
                return ResourceManager.GetString("errFacturasEnlaceContable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La fecha del enlace contable no puede ser posterior a la actual.
        /// </summary>
        public static string errFechaEnlaceContable {
            get {
                return ResourceManager.GetString("errFechaEnlaceContable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario o contraseña incorrectos.
        /// </summary>
        public static string errLogin {
            get {
                return ResourceManager.GetString("errLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ha superado el tamaño máximo del fichero ({0} mb).
        /// </summary>
        public static string errMaxFileSizeUpload {
            get {
                return ResourceManager.GetString("errMaxFileSizeUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se ha superado el importe de la factura.
        /// </summary>
        public static string errPresupuestoFacturaSuperado {
            get {
                return ResourceManager.GetString("errPresupuestoFacturaSuperado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya existe un proveedor con el mismo CIF.
        /// </summary>
        public static string errProveedorCIFExistente {
            get {
                return ResourceManager.GetString("errProveedorCIFExistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo {0} es obligatorio..
        /// </summary>
        public static string errRequerido {
            get {
                return ResourceManager.GetString("errRequerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe seleccionar al menos un concepto de facturación.
        /// </summary>
        public static string errSeleccionarLineaEsfuerzo {
            get {
                return ResourceManager.GetString("errSeleccionarLineaEsfuerzo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Existe otra tarea con ese nombre. El nombre de la tarea debe ser único..
        /// </summary>
        public static string errTareaExistente {
            get {
                return ResourceManager.GetString("errTareaExistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Generar Conceptos.
        /// </summary>
        public static string Etiqueta_GenerarConceptos {
            get {
                return ResourceManager.GetString("Etiqueta_GenerarConceptos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Texto imagen.
        /// </summary>
        public static string lblCaptcha {
            get {
                return ResourceManager.GetString("lblCaptcha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password.
        /// </summary>
        public static string lblPassword {
            get {
                return ResourceManager.GetString("lblPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario.
        /// </summary>
        public static string lblUsuario {
            get {
                return ResourceManager.GetString("lblUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acceso.
        /// </summary>
        public static string litAcceso {
            get {
                return ResourceManager.GetString("litAcceso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enseñanza Formacion Profesional no Superior.
        /// </summary>
        public static string litActividadFormacion {
            get {
                return ResourceManager.GetString("litActividadFormacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Explotacion electronica por cta de terceros.
        /// </summary>
        public static string litActividadGeneral {
            get {
                return ResourceManager.GetString("litActividadGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Activo.
        /// </summary>
        public static string litActivo {
            get {
                return ResourceManager.GetString("litActivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Año.
        /// </summary>
        public static string litAnyo {
            get {
                return ResourceManager.GetString("litAnyo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Año del concepto.
        /// </summary>
        public static string litAnyoConcepto {
            get {
                return ResourceManager.GetString("litAnyoConcepto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Año del presupuesto.
        /// </summary>
        public static string litAnyoPresupuesto {
            get {
                return ResourceManager.GetString("litAnyoPresupuesto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apartado.
        /// </summary>
        public static string litApartado {
            get {
                return ResourceManager.GetString("litApartado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellido 1.
        /// </summary>
        public static string litApellido1 {
            get {
                return ResourceManager.GetString("litApellido1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellido 2.
        /// </summary>
        public static string litApellido2 {
            get {
                return ResourceManager.GetString("litApellido2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aprobación automática.
        /// </summary>
        public static string litAprobacionAutomatica {
            get {
                return ResourceManager.GetString("litAprobacionAutomatica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aprobador.
        /// </summary>
        public static string litAprobador {
            get {
                return ResourceManager.GetString("litAprobador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aprobar.
        /// </summary>
        public static string litAprobar {
            get {
                return ResourceManager.GetString("litAprobar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Base imponible.
        /// </summary>
        public static string litBaseImponible {
            get {
                return ResourceManager.GetString("litBaseImponible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Búsqueda avanzada.
        /// </summary>
        public static string litBusquedaAvanzada {
            get {
                return ResourceManager.GetString("litBusquedaAvanzada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cantidad.
        /// </summary>
        public static string litCantidad {
            get {
                return ResourceManager.GetString("litCantidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cantidad fija.
        /// </summary>
        public static string litCantidadFija {
            get {
                return ResourceManager.GetString("litCantidadFija", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrada.
        /// </summary>
        public static string litCerrada {
            get {
                return ResourceManager.GetString("litCerrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CIF.
        /// </summary>
        public static string litCIF {
            get {
                return ResourceManager.GetString("litCIF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comentarios.
        /// </summary>
        public static string litComentarios {
            get {
                return ResourceManager.GetString("litComentarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Concepto facturación.
        /// </summary>
        public static string litConceptoFacturacion {
            get {
                return ResourceManager.GetString("litConceptoFacturacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contacto.
        /// </summary>
        public static string litContacto {
            get {
                return ResourceManager.GetString("litContacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos empresa.
        /// </summary>
        public static string litDatosEmpresa {
            get {
                return ResourceManager.GetString("litDatosEmpresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos generales.
        /// </summary>
        public static string litDatosGenerales {
            get {
                return ResourceManager.GetString("litDatosGenerales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos solicitud.
        /// </summary>
        public static string litDatosSolicitud {
            get {
                return ResourceManager.GetString("litDatosSolicitud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descargar.
        /// </summary>
        public static string litDescargar {
            get {
                return ResourceManager.GetString("litDescargar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descargar facturas.
        /// </summary>
        public static string litDescargarFacturas {
            get {
                return ResourceManager.GetString("litDescargarFacturas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descargar plantilla.
        /// </summary>
        public static string litDescargarPlantilla {
            get {
                return ResourceManager.GetString("litDescargarPlantilla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción.
        /// </summary>
        public static string litDescripcion {
            get {
                return ResourceManager.GetString("litDescripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desde.
        /// </summary>
        public static string litDesde {
            get {
                return ResourceManager.GetString("litDesde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Detalle de la factura.
        /// </summary>
        public static string litDetalleFactura {
            get {
                return ResourceManager.GetString("litDetalleFactura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Detalle del pedido.
        /// </summary>
        public static string litDetallePedido {
            get {
                return ResourceManager.GetString("litDetallePedido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Detalle de la tarea.
        /// </summary>
        public static string litDetalleTarea {
            get {
                return ResourceManager.GetString("litDetalleTarea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dirección.
        /// </summary>
        public static string litDireccion {
            get {
                return ResourceManager.GetString("litDireccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Documento.
        /// </summary>
        public static string litDocumento {
            get {
                return ResourceManager.GetString("litDocumento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edición.
        /// </summary>
        public static string litEdicion {
            get {
                return ResourceManager.GetString("litEdicion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar.
        /// </summary>
        public static string litEditar {
            get {
                return ResourceManager.GetString("litEditar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Elementos.
        /// </summary>
        public static string litElementos {
            get {
                return ResourceManager.GetString("litElementos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar.
        /// </summary>
        public static string litEliminar {
            get {
                return ResourceManager.GetString("litEliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email.
        /// </summary>
        public static string litEmail {
            get {
                return ResourceManager.GetString("litEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Emitir factura.
        /// </summary>
        public static string litEmitirFactura {
            get {
                return ResourceManager.GetString("litEmitirFactura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Emitir pedido.
        /// </summary>
        public static string litEmitirPedido {
            get {
                return ResourceManager.GetString("litEmitirPedido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Esta empleando un navegador web no soportado.
        /// </summary>
        public static string litEmpleandoNavegadorNoSoportado {
            get {
                return ResourceManager.GetString("litEmpleandoNavegadorNoSoportado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Empresa.
        /// </summary>
        public static string litEmpresa {
            get {
                return ResourceManager.GetString("litEmpresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Empresa a facturar.
        /// </summary>
        public static string litEmpresaFacturar {
            get {
                return ResourceManager.GetString("litEmpresaFacturar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Empresas.
        /// </summary>
        public static string litEmpresas {
            get {
                return ResourceManager.GetString("litEmpresas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error.
        /// </summary>
        public static string litError {
            get {
                return ResourceManager.GetString("litError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ha ocurrido un error en la aplicación. .
        /// </summary>
        public static string litErrorDescripcion {
            get {
                return ResourceManager.GetString("litErrorDescripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado.
        /// </summary>
        public static string litEstado {
            get {
                return ResourceManager.GetString("litEstado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Expediente/referencia de pedido.
        /// </summary>
        public static string litExpedienteReferencia {
            get {
                return ResourceManager.GetString("litExpedienteReferencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exportar conceptos.
        /// </summary>
        public static string litExportarConceptos {
            get {
                return ResourceManager.GetString("litExportarConceptos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exportar a Excel.
        /// </summary>
        public static string litExportarExcel {
            get {
                return ResourceManager.GetString("litExportarExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Factura.
        /// </summary>
        public static string litFactura {
            get {
                return ResourceManager.GetString("litFactura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Facturado.
        /// </summary>
        public static string litFacturado {
            get {
                return ResourceManager.GetString("litFacturado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Facturas pendientes de aprobación.
        /// </summary>
        public static string litFacturasPendientesAprobacion {
            get {
                return ResourceManager.GetString("litFacturasPendientesAprobacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha.
        /// </summary>
        public static string litFecha {
            get {
                return ResourceManager.GetString("litFecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha aprobación.
        /// </summary>
        public static string litFechaAprobacion {
            get {
                return ResourceManager.GetString("litFechaAprobacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de creación.
        /// </summary>
        public static string litFechaCreacion {
            get {
                return ResourceManager.GetString("litFechaCreacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha emisión.
        /// </summary>
        public static string litFechaEmision {
            get {
                return ResourceManager.GetString("litFechaEmision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha enlace.
        /// </summary>
        public static string litFechaEnlace {
            get {
                return ResourceManager.GetString("litFechaEnlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha del pedido.
        /// </summary>
        public static string litFechaPedido {
            get {
                return ResourceManager.GetString("litFechaPedido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha solicitud.
        /// </summary>
        public static string litFechaSolicitud {
            get {
                return ResourceManager.GetString("litFechaSolicitud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha vencimiento.
        /// </summary>
        public static string litFechaVencimiento {
            get {
                return ResourceManager.GetString("litFechaVencimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Filtros.
        /// </summary>
        public static string litFiltros {
            get {
                return ResourceManager.GetString("litFiltros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar.
        /// </summary>
        public static string litGuardar {
            get {
                return ResourceManager.GetString("litGuardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar y nuevo.
        /// </summary>
        public static string litGuardarYNuevo {
            get {
                return ResourceManager.GetString("litGuardarYNuevo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hasta.
        /// </summary>
        public static string litHasta {
            get {
                return ResourceManager.GetString("litHasta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Id.
        /// </summary>
        public static string litID {
            get {
                return ResourceManager.GetString("litID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Importar.
        /// </summary>
        public static string litImportar {
            get {
                return ResourceManager.GetString("litImportar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Importar conceptos.
        /// </summary>
        public static string litImportarConceptos {
            get {
                return ResourceManager.GetString("litImportarConceptos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Importar facturas.
        /// </summary>
        public static string litImportarFacturasP {
            get {
                return ResourceManager.GetString("litImportarFacturasP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Importe.
        /// </summary>
        public static string litImporte {
            get {
                return ResourceManager.GetString("litImporte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Importe IVA.
        /// </summary>
        public static string litImporteIVA {
            get {
                return ResourceManager.GetString("litImporteIVA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Importe (sin IVA).
        /// </summary>
        public static string litImporteSinIVA {
            get {
                return ResourceManager.GetString("litImporteSinIVA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Importe total.
        /// </summary>
        public static string litImporteTotal {
            get {
                return ResourceManager.GetString("litImporteTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Importe unitario.
        /// </summary>
        public static string litImporteUnitario {
            get {
                return ResourceManager.GetString("litImporteUnitario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Item number (D365).
        /// </summary>
        public static string litItemNumberD365 {
            get {
                return ResourceManager.GetString("litItemNumberD365", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a IVA.
        /// </summary>
        public static string litIVA {
            get {
                return ResourceManager.GetString("litIVA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Limpiar.
        /// </summary>
        public static string litLimpiar {
            get {
                return ResourceManager.GetString("litLimpiar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Limpiar filtros.
        /// </summary>
        public static string litLimpiarFiltros {
            get {
                return ResourceManager.GetString("litLimpiarFiltros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Conceptos de facturación pendientes de aprobación.
        /// </summary>
        public static string litLineasEsfuerzoPendientesAprobacion {
            get {
                return ResourceManager.GetString("litLineasEsfuerzoPendientesAprobacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Conceptos de facturación seleccionados:.
        /// </summary>
        public static string litLineasEsfuerzoSeleccionadas {
            get {
                return ResourceManager.GetString("litLineasEsfuerzoSeleccionadas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exportar Facturas y Conceptos.
        /// </summary>
        public static string litListadoFacturasConceptos {
            get {
                return ResourceManager.GetString("litListadoFacturasConceptos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exportar Pedidos y Conceptos.
        /// </summary>
        public static string litListadoPedidosConceptos {
            get {
                return ResourceManager.GetString("litListadoPedidosConceptos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Login.
        /// </summary>
        public static string litLogin {
            get {
                return ResourceManager.GetString("litLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configuración.
        /// </summary>
        public static string litMenuConfiguracion {
            get {
                return ResourceManager.GetString("litMenuConfiguracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enlace contable.
        /// </summary>
        public static string litMenuEnlaceContable {
            get {
                return ResourceManager.GetString("litMenuEnlaceContable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Facturación.
        /// </summary>
        public static string litMenuFacturacion {
            get {
                return ResourceManager.GetString("litMenuFacturacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Facturas.
        /// </summary>
        public static string litMenuFacturas {
            get {
                return ResourceManager.GetString("litMenuFacturas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Facturas proveedor.
        /// </summary>
        public static string litMenuFacturasP {
            get {
                return ResourceManager.GetString("litMenuFacturasP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inicio.
        /// </summary>
        public static string litMenuInicio {
            get {
                return ResourceManager.GetString("litMenuInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Item Numbers D365.
        /// </summary>
        public static string litMenuItemNumbersD365 {
            get {
                return ResourceManager.GetString("litMenuItemNumbersD365", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Conceptos de facturación.
        /// </summary>
        public static string litMenuLineasEsfuerzo {
            get {
                return ResourceManager.GetString("litMenuLineasEsfuerzo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mantenimientos.
        /// </summary>
        public static string litMenuMantenimientos {
            get {
                return ResourceManager.GetString("litMenuMantenimientos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pedidos.
        /// </summary>
        public static string litMenuPedidos {
            get {
                return ResourceManager.GetString("litMenuPedidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Perfiles.
        /// </summary>
        public static string litMenuPerfiles {
            get {
                return ResourceManager.GetString("litMenuPerfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Personas.
        /// </summary>
        public static string litMenuPersonas {
            get {
                return ResourceManager.GetString("litMenuPersonas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Portal.
        /// </summary>
        public static string litMenuPortal {
            get {
                return ResourceManager.GetString("litMenuPortal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Productos D365.
        /// </summary>
        public static string litMenuProductosD365 {
            get {
                return ResourceManager.GetString("litMenuProductosD365", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proveedores.
        /// </summary>
        public static string litMenuProveedores {
            get {
                return ResourceManager.GetString("litMenuProveedores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tareas.
        /// </summary>
        public static string litMenuTareas {
            get {
                return ResourceManager.GetString("litMenuTareas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuarios.
        /// </summary>
        public static string litMenuUsuarios {
            get {
                return ResourceManager.GetString("litMenuUsuarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mes del concepto.
        /// </summary>
        public static string litMesConcepto {
            get {
                return ResourceManager.GetString("litMesConcepto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Navegado no soportado.
        /// </summary>
        public static string litNavegadorNoSoportado {
            get {
                return ResourceManager.GetString("litNavegadorNoSoportado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No.
        /// </summary>
        public static string litNo {
            get {
                return ResourceManager.GetString("litNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        public static string litNombre {
            get {
                return ResourceManager.GetString("litNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo.
        /// </summary>
        public static string litNuevo {
            get {
                return ResourceManager.GetString("litNuevo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nº factura.
        /// </summary>
        public static string litNumFactura {
            get {
                return ResourceManager.GetString("litNumFactura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nº pedido.
        /// </summary>
        public static string litNumPedido {
            get {
                return ResourceManager.GetString("litNumPedido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pedido.
        /// </summary>
        public static string litPedido {
            get {
                return ResourceManager.GetString("litPedido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Perfil.
        /// </summary>
        public static string litPerfil {
            get {
                return ResourceManager.GetString("litPerfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Persona.
        /// </summary>
        public static string litPersona {
            get {
                return ResourceManager.GetString("litPersona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por horas.
        /// </summary>
        public static string litPorHoras {
            get {
                return ResourceManager.GetString("litPorHoras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por unidades.
        /// </summary>
        public static string litPorUnidades {
            get {
                return ResourceManager.GetString("litPorUnidades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Presupuesto.
        /// </summary>
        public static string litPresupuesto {
            get {
                return ResourceManager.GetString("litPresupuesto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Presupuesto consumido.
        /// </summary>
        public static string litPresupuestoConsumido {
            get {
                return ResourceManager.GetString("litPresupuestoConsumido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Presupuesto restante.
        /// </summary>
        public static string litPresupuestoRestante {
            get {
                return ResourceManager.GetString("litPresupuestoRestante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Presupuesto - Unidades.
        /// </summary>
        public static string litPresupuestoUnidades {
            get {
                return ResourceManager.GetString("litPresupuestoUnidades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Producto (D365).
        /// </summary>
        public static string litProductoD365 {
            get {
                return ResourceManager.GetString("litProductoD365", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proveedor.
        /// </summary>
        public static string litProveedor {
            get {
                return ResourceManager.GetString("litProveedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Realizado por.
        /// </summary>
        public static string litRealizadoPor {
            get {
                return ResourceManager.GetString("litRealizadoPor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rechazar.
        /// </summary>
        public static string litRechazar {
            get {
                return ResourceManager.GetString("litRechazar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Refrescar.
        /// </summary>
        public static string litRefrescar {
            get {
                return ResourceManager.GetString("litRefrescar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Requiere aprobación.
        /// </summary>
        public static string litRequiereAprobacion {
            get {
                return ResourceManager.GetString("litRequiereAprobacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sección.
        /// </summary>
        public static string litSeccion {
            get {
                return ResourceManager.GetString("litSeccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccionar.
        /// </summary>
        public static string litSeleccionar {
            get {
                return ResourceManager.GetString("litSeleccionar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione los conceptos de facturación a incluir:.
        /// </summary>
        public static string litSeleccioneLineasEsfuerzo {
            get {
                return ResourceManager.GetString("litSeleccioneLineasEsfuerzo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sesión caducada.
        /// </summary>
        public static string litSesionCaducada {
            get {
                return ResourceManager.GetString("litSesionCaducada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La sesión ha caducado por inactividad..
        /// </summary>
        public static string litSesionCaducadaDescripcion {
            get {
                return ResourceManager.GetString("litSesionCaducadaDescripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Si.
        /// </summary>
        public static string litSi {
            get {
                return ResourceManager.GetString("litSi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No hay registros.
        /// </summary>
        public static string litSinRegistros {
            get {
                return ResourceManager.GetString("litSinRegistros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solicitante.
        /// </summary>
        public static string litSolicitante {
            get {
                return ResourceManager.GetString("litSolicitante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tarea.
        /// </summary>
        public static string litTarea {
            get {
                return ResourceManager.GetString("litTarea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo.
        /// </summary>
        public static string litTipo {
            get {
                return ResourceManager.GetString("litTipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unidad.
        /// </summary>
        public static string litUnidad {
            get {
                return ResourceManager.GetString("litUnidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unidades.
        /// </summary>
        public static string litUnidades {
            get {
                return ResourceManager.GetString("litUnidades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario.
        /// </summary>
        public static string litUsuario {
            get {
                return ResourceManager.GetString("litUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valor.
        /// </summary>
        public static string litValor {
            get {
                return ResourceManager.GetString("litValor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver detalle.
        /// </summary>
        public static string litVerDetalle {
            get {
                return ResourceManager.GetString("litVerDetalle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver todo.
        /// </summary>
        public static string litVerTodo {
            get {
                return ResourceManager.GetString("litVerTodo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Visible.
        /// </summary>
        public static string litVisible {
            get {
                return ResourceManager.GetString("litVisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Volver.
        /// </summary>
        public static string litVolver {
            get {
                return ResourceManager.GetString("litVolver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pedidos de venta SSCC - Solicitud de factura.
        /// </summary>
        public static string msgAsuntoMailSolicitudFactura {
            get {
                return ResourceManager.GetString("msgAsuntoMailSolicitudFactura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pedidos de venta SSCC - Solicitud de alta de concepto de facturación.
        /// </summary>
        public static string msgAsuntoMailSolicitudLineaEsfuerzo {
            get {
                return ResourceManager.GetString("msgAsuntoMailSolicitudLineaEsfuerzo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La fecha de emisión de la factura es anterior a la fecha del último enlace. ¿Desea continuar?.
        /// </summary>
        public static string msgConfirmFechaEmisionEnlace {
            get {
                return ResourceManager.GetString("msgConfirmFechaEmisionEnlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ha ocurrido un error al eliminar el registro.
        /// </summary>
        public static string msgEliminarError {
            get {
                return ResourceManager.GetString("msgEliminarError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar.
        /// </summary>
        public static string msgEliminarErrorTitulo {
            get {
                return ResourceManager.GetString("msgEliminarErrorTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Escriba aquí el texto a buscar.
        /// </summary>
        public static string msgEscribeParaBuscar {
            get {
                return ResourceManager.GetString("msgEscribeParaBuscar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ha ocurrido un error al registrar la información.
        /// </summary>
        public static string msgGuardarError {
            get {
                return ResourceManager.GetString("msgGuardarError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ha ocurrido un error al registrar la información debido a que no es editable.
        /// </summary>
        public static string msgGuardarErrorNoEditable {
            get {
                return ResourceManager.GetString("msgGuardarErrorNoEditable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar.
        /// </summary>
        public static string msgGuardarErrorTitulo {
            get {
                return ResourceManager.GetString("msgGuardarErrorTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se ha registrado la información correctamente.
        /// </summary>
        public static string msgGuardarOK {
            get {
                return ResourceManager.GetString("msgGuardarOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar.
        /// </summary>
        public static string msgGuardarOKTitulo {
            get {
                return ResourceManager.GetString("msgGuardarOKTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La importación se ha realizado con algunos errores. Consulte el fichero generado..
        /// </summary>
        public static string msgImportacionErrores {
            get {
                return ResourceManager.GetString("msgImportacionErrores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione factura.
        /// </summary>
        public static string msgSeleccionaFactura {
            get {
                return ResourceManager.GetString("msgSeleccionaFactura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione proveedor.
        /// </summary>
        public static string msgSeleccionaProveedor {
            get {
                return ResourceManager.GetString("msgSeleccionaProveedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione tarea-empresa.
        /// </summary>
        public static string msgSeleccionaTareaEmpresa {
            get {
                return ResourceManager.GetString("msgSeleccionaTareaEmpresa", resourceCulture);
            }
        }
    }
}
